---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: root
    group: root
  loop:
    - "{{ self_signed_certificate_key_path }}"
    - "{{ self_signed_certificate_csr_path }}"
    - "{{ self_signed_certificate_path }}"

- name: Install python OpenSSL on Debian/Ubuntu
  apt:
    name: python{{ "3" if ansible_python.version.major == 3 }}-openssl
    state: present
  register: apt_result
  until: apt_result is succeeded
  retries: 3
  when: ansible_os_family == "Debian"

- name: Install python OpenSSL on Fedora
  yum:
    name: python{{ "3" if ansible_python.version.major == 3 }}-cryptography
    state: present
  register: yum_result
  until: yum_result is succeeded
  retries: 3
  when: ansible_os_family == "RedHat"

- name: Generate OpenSSL private key
  openssl_privatekey:
    path: "{{ self_signed_certificate_key_path }}/privkey.pem"
    type: "{{ self_signed_certificate_key_type }}"
    size: "{{ self_signed_certificate_key_size }}"
    state: present
    mode: 0640
    group: root
    owner: root

- name: Generate OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{ self_signed_certificate_csr_path }}/{{ self_signed_certificate_FQDN | first }}.csr"
    privatekey_path: "{{ self_signed_certificate_key_path }}/privkey.pem"
    digest: "{{ self_signed_certificate_csr_digest }}"
    email_address: "{{ self_signed_certificate_email }}"
    common_name: "{{ self_signed_certificate_FQDN | first }}"
    subject_alt_name: "DNS:{{ self_signed_certificate_FQDN | join(',DNS:') }}"
    locality_name: "{{ self_signed_certificate_city | default(omit) }}"
    state_or_province_name: "{{ self_signed_certificate_state | default(omit) }}"
    country_name: "{{ self_signed_certificate_country | default(omit) }}"
    organization_name: "{{ self_signed_certificate_organisation | default(omit) }}"
    organizational_unit_name: "{{ self_signed_certificate_organizational_unit | default(omit) }}"
    state: present

- name: Generate self-signed OpenSSL certificate
  openssl_certificate:
    path: "{{ self_signed_certificate_path }}/fullchain.pem"
    privatekey_path: "{{ self_signed_certificate_key_path }}/privkey.pem"
    csr_path: "{{ self_signed_certificate_csr_path }}/{{ self_signed_certificate_FQDN | first }}.csr"
    provider: selfsigned
    selfsigned_digest: "{{ self_signed_certificate_digest }}"
    selfsigned_not_after: "{{ self_signed_certificate_not_after }}"
    state: present
...
